axelarnetwork/axelarate-community

- Exercises/exercise_2_btc_transfer_with_c2d2.md
- TESTNET RELEASE.md
This is a draft version of c2d2 exercise, which will be updated as the progress of c2d2 . Meanwhile, feel free to point out any confusion/error.
> docs: exercise for c2d2

- CHANGELOG.md
- Exercises/exercise_1_btc_transfer_cli.md
- README.md
- TESTNET RELEASE.md
- change axelar-core release to 0.3.2
- add details to the exercise about which outpoint to confirm
> docs: update for 0.3.2

- c2d2/c2d2cli.sh
- c2d2/config.sh
- c2d2/config.toml
* fix issue with internal host not available. Host mode is fine for now so we don't have to use the internal host domain mapping.
> chore: replace docker.internal.host with localhost

- Exercises/exercise_1_btc_transfer_cli.md
This PR should be merged once the next version of Axelar-core is shipped. The instructions are updated to reflect the new info logging message
> refactor: update instructions with new logging message

- c2d2/config.sh
> fix(c2d2): make script POSIX compliant

- EXTRA COMMANDS.md
Status: Ready to merge
Update the query instructions in axelarate-community to match the query cli changes in axelar-core
Testing: all query instructions were tested manually on the testnet
> doc: update query commands

- README.md
Update the check balance command so user doesn't need to edit in address, but gets retrieved automatically.
> readme - check balance with nested command

- Exercises/exercise_2_btc_transfer_with_c2d2.md
Added extra detail to step 1 of Mint ERC20 Bitcoin tokens on Ethereum.
> Added clarity to exercise 2 docs

- documentation/docs/Exercises/Exercise 3.md
- documentation/docs/Exercises/Exercise 4.md
- documentation/docs/Exercises/Exercise 5.md
- documentation/package-lock.json
- documentation/package.json
Just did  a `Ctrl + A` and `Shift+Tab` to fix indentation and added bash so that the framework could identify the language to highlight.
> fix indentation and prettify code

- join/joinTestnet.sh
- join/launchValidator.sh
fix docker network issue by having the network explicitly created before launching the axelar-core container
> fix(scripts): docker network

- documentation/docs/Exercises/Exercise 5.md
> Update Exercise 5.md

- documentation/docs/Exercises/Exercise 4.md
bunch of links lead to 404 so updated it
> Update Exercise 4.md

- documentation/docs/Exercises/Exercise 4.md
This reverts commit d8b0f53d903c0f1a37c9e405fa29b919d45f81dc.
> revert: "Update Exercise 4.md (#159)"

- documentation/Admin/Exercise 3 Join Validator.md
- documentation/Admin/btc-consolidation-transaction.md
- documentation/Admin/btc-key-rotation.md
- join/launch-validator-with-binaries.sh
Depends on https://github.com/axelarnetwork/kms/pull/18
> docs: btc master key rotation

- documentation/docs/Common Problems And Their Solutions/Instructions.md
- documentation/docs/Common Problems And Their Solutions/Problem1.md
- documentation/docs/Common Problems And Their Solutions/Problem2.md
- documentation/docs/Common Problems And Their Solutions/Problem3.md
- documentation/docs/Common Problems And Their Solutions/Problem4.md
- documentation/docs/Common Problems And Their Solutions/Problem5.md
- documentation/docs/Common Problems And Their Solutions/Problem6.md
- documentation/docs/Common Problems And Their Solutions/Problem7.md
- documentation/docs/Common Problems And Their Solutions/Problem8.md
- documentation/docs/Common Problems And Their Solutions/UsefulLinks.md
Kate suggested to move the FAQ doc to the documentation site as well
https://discord.com/channels/770814806105128977/855477983938215986/888167244058755123
> add faq to documentation site

- documentation/Admin/join-as-validator-binaries.md
- documentation/Admin/join-as-validator-docker.md
- documentation/docs/Exercises/Exercise 1.md
- documentation/docs/Exercises/Exercise 2.md
- documentation/docs/Exercises/Exercise 3.md
- documentation/docs/Exercises/Exercise 4.md
- documentation/docs/Exercises/Exercise 5.md
- documentation/docs/setup-with-binaries.md
- documentation/docs/setup-with-docker.md
http://faucet.testnet.axelar.network/ is no longer active.  Update to http://faucet.testnet.axelar.dev/
> fix: faucet links

- join/launch-validator-with-binaries.sh
- join/launch-validator.sh
Prepare axelarate-community to incorporate new mnemonic spec for tofnd release 0.7.
Don't merge this until tofnd v0.7 is released.
> feat: update cmd for tofnd to auto

- join/launch-validator-tools.sh
> fix(scripts): update config.toml using launch-validators-tools.sh

- documentation/docs/Exercises/Exercise 6.md
Exercise 6 is about validator setup.  We already have docs about that, so this exercise simply redirects to the existing docs.
> doc: add exercise 6 on validator setup

- join/app.toml
- join/config.toml
Update tomls to match state of cosmos-sdk 0.44.x
> chore: update tomls

- documentation/Admin/evm-key-rotation.md
Add instructions for fetching EVM gateway-address before sending transaction hex data.
Add instructions for increasing transaction gas limit
> docs: update evm key rotation

- documentation/Admin/evm-key-rotation.md
Increase the suggested ethereum gas fee in case the validator set grows in the future
> doc: update evm key rotation gas fee suggestion

- documentation/docs/Exercises/Exercise 4.md
- documentation/docs/setup-with-binaries.md
- documentation/docs/setup-with-docker.md
- documentation/docs/testnet-releases.md
- documentation/docs/validator-zone/setup/stake-axl-tokens.md
- join/consumeGenesis.sh
- join/initVald.sh
- join/join-testnet-with-binaries.sh
- join/join-testnet.sh
- join/launch-validator-tools-with-binaries.sh
> doc: add more tips

- documentation/docs/upgrade-v0.8.5.md
- documentation/docs/validator-zone/troubleshoot/missed-too-many-blocks.md
- documentation/docs/validator-zone/troubleshoot/unjail.md
Is everything correct?  Is there something more I should add?
> doc: fix jail, add missed-too-many-blocks

- join/config.toml
ported manually from https://github.com/rooiie/axelarate-community/tree/patch-1 due to permission issues @rooiie
> chore: tidy, comment, add template sections for more evm chains

- join/join-testnet-with-binaries.sh
- join/launch-validator-tools-with-binaries.sh
Should fix this: https://discord.com/channels/770814806105128977/867457262620770334/920579127147388948
> Chain id fix

- documentation/docs/resources/testnet-releases.md
after merge: push tag for v0.9.1
> chore: bump version to 0.9.1

- join/enforce_backup.sh
- join/join-testnet-with-binaries.sh
- join/join-testnet.sh
- join/launch-validator-tools-with-binaries.sh
- join/launch-validator-tools.sh
Enforce users to delete their mnemonics before continuing.
> chore: enforce user to backup mnemonics

- README.md
see #298 .  We should fix the script in a separate PR.
> doc: mention password min length

- UPGRADE.md
- resources/testnet-releases.md
> doc: lisbon-2 upgrade instructions

- scripts/node.sh
port axelarnetwork/validators#20
> fix: make external_address non-mandatory

- configuration/vald-entrypoint.sh
- scripts/node.sh
- scripts/validator-tools-docker.sh
- scripts/validator-tools-host.sh
* allow users to join mainnet from `node.sh`
* set `root_directory` according to testnet/mainnet
* allow user to abort if they don't like the parameters
> feat: add mainnet to node.sh

- README.md
add link to docs website with info for bug bounty and secure vulnerability disclosure
> doc: add bug bounty info

- UPGRADE.md
- A validator needs to run both scripts during update.
> feat: add notes on running both scripts

- resources/hacknet/genesis.json
- resources/hacknet/seeds.txt
- scripts/host.sh
- scripts/node.sh
Use `-n hacknet` to join the hacknet like this:
```bash
KEYRING_PASSWORD=my-secret-password ./scripts/node.sh -n hacknet
```
Tested on my local machine.
- For hacknet fetch `genesis.json` and `seeds.txt` from this repo instead of s3.
- No support for docker
- No support for validator join
> feat: add hacknet network to node.sh join script

- resources/mainnet/seeds.toml
Just fixing sintax, without this is not possible to start a node in mainnet.
> Fixing sintax

- resources/mainnet/seeds.toml
- resources/mainnet/seeds.txt
We updated the p-ops seed node
> update pops seed node

- scripts/setup-node.sh
Fix the issue described here : https://github.com/axelarnetwork/axelarate-community/issues/397
> fix: path in setup-node.sh

- scripts/host.sh
- scripts/node.sh
- scripts/setup-host.sh
- scripts/setup-node.sh
- download and dynamically link `libwasmvm`  to axelard binary
> feat: download and dynamically link libwasmvm to axelard binary 
