- README.md
- join/joinTestnet.sh
* Used 4 space indent on code blocks and text underneath numbered lists so it appears indented under each numbered item instead of looking like one left aligned runaway section.
* `--reset-chain` argument for `join/joinTestnet.sh` is dangerous due to lack of proper shell variable quoting and allows for accidentally deleting far more data than just the Axelar root directory under the right circumstances. Directories with spaces in them would have removed two levels of directories, e.g. `rm -rf /first/absolute/path second/relative/path` vs `rm -rf "/one/path with/spaces/"`.
> Fix README formatting and bug in `--reset-chain` `join/joinTestnet.sh` argument.

- join/joinTestnet.sh
The cosmos stargate update changed the folder structure for data persistence. Consequently those new folders were not mapped to the host system anymore and progress was lost whenever the container was deleted. This commit maps the correct folders again.
> fix: map correct folders to allow data persistence

- Exercises/exercise_2_btc_transfer_with_c2d2.md
- README.md
General README updates such as restarting without synching, finding axelar core and tofnd versions from TESTNET RELEASE instead of docker.
Change latest c2d2 version to 0.1.5
Small c2d2 instruction changes
Please give feedback if you disagree :)
> doc: update some instructions

- README.md
- added command to check sync info
- changed `validator_addr` to `output_addr_from_step_2`, as `validator_addr` sounds a little confusing and people may later confuse it with the actual validator address ie `axelarvaloper..`
- added instruction to setup software prerequisites
> add command to check sync status and add software prerequisites

- BTC ETH NODE SETUP.md
- Exercises/exercise_3_join_validator.md
Add instructions for users to set up their own Bitcoin and Ethereum testnet nodes, and connect the RPC endpoint to Axelar. Related to #87 .
Status: Complete, awaiting potential feedback
Testing: Manual, follow exercise 3 instructions
> doc: add bitcoin ethereum node setup instructions to exercise 3

- BTC ETH NODE SETUP.md
- Exercises/exercise_3_join_validator.md
- README.md
Status: Ready to merge
Description:
Currently, some testnet validators are failing keygen because of timeout, because vald cannot connect to tofnd. This PR updates the ex3 instructions to include a series of checks which help to determine if valid/tofnd are configured and running properly, as well as steps to fix the connection issue.
Some other minor instruction updates are included
Testing: manual testing done by following the new instructions
> doc: instruction updates for exercise 3

- Admin/exercise_3_join_validator.md
Status: Ready to merge
Description: 
Currently, any testnet participant can read exercise 3 and attempt to become a validator. The goal is to only have approved people joining as validator for now.
Moving to Admin folder gives ex3 less visibility and this PR also adds team approval as a prerequisite before starting ex3
> chore(ex3): move exercise 3 to Admin folder

- join/joinTestnet.sh
As of [this tofnd commit](https://github.com/axelarnetwork/tofnd/commit/9bd8c11c1390af8178aae976b76601bf71ed0c96) tofnd now stores all local data in `/.tofnd`.  This PR reflects this change: `.kvstore -> .tofnd`.  Need to synchronize this PR with the next version of testnet.
> fix(tofnd): point to new tofnd local path root

- documentation/docs/setup.md
tested locally:
```
$ TOFND_VERSION=$(curl -s https://raw.githubusercontent.com/axelarnetwork/axelarate-community/main/documentation/docs/testnet-releases.md | grep tofnd | cut -d \` -f 4)
$ CORE_VERSION=$(curl -s https://raw.githubusercontent.com/axelarnetwork/axelarate-community/main/documentation/docs/testnet-releases.md  | grep axelar-core | cut -d \` -f 4) 
$ echo ${TOFND_VERSION} ${CORE_VERSION}
v0.4.0 v0.5.2
```
> Update setup.md for correct path to release

- .gitignore
- documentation/Admin/validator_backup.md
- documentation/Admin/validator_recovery.md
- join/join-testnet-with-binaries.sh
- join/launch-validator-with-binaries.sh
The tofnd binary does not allow changing the name of the home directory. so the home directory ends up being ~/.tofnd and ./.tofnd. This needs to be fixed in the future.
The idea is that this brings us to parity with the joinTestnet.sh and launchValidator.sh scripts.
Will need help from @jcs47 to test this properly.
> chore: add script to join testnet with binaries

- documentation/docs/Exercises/Exercise 3.md
- documentation/docs/Exercises/Exercise 4.md
- Add `--packet-timeout-timestamp  0` in ibc-transfer command
- Move `not send the whole amount` tip to the beginning of step 2
- Reduce sample withdrawal amount
- Add one more search for outpoint
> chore: improve based on suggestion

- join/join-testnet-with-binaries.sh
- join/launch-validator-with-binaries.sh
Allow script to fail when binary not downloaded
Override arch with amd64 when its x86_64
> fix(script): replace OS not ARCH variable

- documentation/Admin/join-as-validator-binaries.md
- documentation/Admin/join-as-validator-docker.md
A community member on the discord chat in the validators channel mentioned this broken link that needs to be updated.
> docs: updating links for eth-btc-node-setup.md

- documentation/Admin/validator-extra-commands.md
- documentation/docs/Common Problems And Their Solutions/_category_.json
- documentation/docs/Exercises/Exercise 1.md
- documentation/docs/Exercises/Exercise 2.md
- documentation/docs/Exercises/Exercise 3.md
- documentation/docs/Exercises/Exercise 4.md
- documentation/docs/Exercises/Exercise 5.md
- documentation/docs/Exercises/_category_.json
- documentation/docs/extra-commands.md
- documentation/docs/setup-with-docker.md
- documentation/docs/testnet-releases.md
- documentation/docs/welcome.md
- documentation/docusaurus.config.js
Currently, the Github repo and the Vercel website are out of sync because Vercel deployments are failing due to broken links.
This PR fixes these broken links to update the website with our latest github changes. In the future, we will enforce a passing check from vercel bot before allowing PR merge
> fix: broken links to setup page

- join/join-testnet.sh
Some users accidentally run `join-testnet.sh` from `main` branch instead of the appropriate version tag.  This PR makes `join-testnet.sh` terminate with an error:
```
Please checkout the correct version tag. See README for instructions.
```
unless the user sets the `--dev` flag.
> chore: add --dev flag to prevent accidental use of main branch

- join/join-testnet.sh
Adding pause allow the axelar-core container to run long enough so the docker exec  can run with success later.
> [join-Testnet.sh] add pause after docker run

- documentation/docs/validator-zone/setup/register-proxy.md
- join/launch-validator-tools.sh
* `sleep 2s` -> `sleep 2`
* broken link in docs
> fix: launch-validator-tools.sh

- documentation/docs/testnet-releases.md
- documentation/docs/upgrade-v0.8.5.md
Note: the flag `--axelar-core v0.8.5` is not actually necessary after this merge.  For simplicity we might remove it from the docs.  I put it there only for clarity to users.
> doc: Upgrade axelar-core to v0.8.5

- documentation/docs/validator-zone/external-chains/overview.md
Add instructions for how to make a validator node into a chain maintainer for Avalanche.
> doc: add avalanche chain maintainer instructions

- documentation/docs/Exercises/Exercise 4.md
This PR addresses a testnet moderator request:
> seems like some members that are running binaries, get confused during the exercises and don't add the required `$HOME/.axelar_testnet/bin` or `--home` flags when running axelard commands. Could we perhaps add another note about this in exercise guides?
> doc: clarify binaries commands for ex4

- resources/testnet-releases.md
> chore: update testnet releases for lisbon-2

- scripts/node.sh
The code reassigned variable `root_directory` again when checking testnet. Thus, it overrides users' argument.
> fix/root_directory not assigned correctly for node.sh

- scripts/node.sh
#330 doesn't work if user passes `-n mainnet`.  This PR reverts #330 and instead checks `root_directory` and `chain_id` before setting as suggested in https://github.com/axelarnetwork/axelarate-community/pull/330#discussion_r795918845
EDIT: Tested locally to verify that env vars are properly set with all combos of `-n` `-d` `-c`.
> fix: revert #330 and instead check before overwriting

- scripts/utils.sh
PR to fix setup-node.sh for genesis sync : https://docs.axelar.dev/node/join-genesis
- setup-node.sh will call utils.sh. 
- We build the line in the expected format, a comma separated list of seed nodes
- We inject it in config.toml 
- We remove the config.toml.bak (created because on Mac you have to create backup file with sed), it is a Mac specificity.
if the binary version is inferior to 0.17, config.toml  file will be used and seeds will be found. If it superior, seeds.toml (current behaviour) will be used. Comparing the versions before injecting the line should not be required.
> fix: add seeds to config.toml

- scripts/node.sh
- scripts/setup-host.sh
- scripts/setup-node.sh
axelard v1.2.1 updates wasmvm version to v1.5.8, requiring a binary runner update in dynamic linking
> chore: update wasmvm dependency
